sudo: false
language: generic

matrix:
    include:

        # Linux, Python 2.7
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10.4
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.14

        # Linux, Python 3.5
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.14

        # Linux, Python 3.6
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.14


addons:
    apt:
        packages:
            - gfortran


install:
    # FSPS
    - git clone https://github.com/cconroy20/fsps libfsps
    - cd libfsps/src
    - cp ../../.travis.Makefile Makefile
    - make all
    - cd ../..
    - export SPS_HOME=`pwd`/libfsps

    # Python
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create --yes -n test python=$PYTHON_VERSION numpy==$NUMPY_VERSION pytest pip
    - source activate test

    # Python FSPS
    - python setup.py build_ext --inplace

script:
    - travis_wait 30 py.test -v fsps/tests.py
