sudo: false

env:
    global:
        - NUMPY_VERSION=1.11

    matrix:
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.4
        - PYTHON_VERSION=3.5

addons:
    apt:
        packages:
            - gfortran


install:
    # FSPS
    - git clone https://github.com/cconroy20/fsps libfsps
    - cd libfsps/src
    - F90FLAGS="-O -cpp -fPIC" make all
    - cd ../..
    - export SPS_HOME=`pwd`/libfsps
    - echo $SPS_HOME
    - ls $SPS_HOME/src

    # Python
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create --yes -n test python=$PYTHON_VERSION numpy==$NUMPY_VERSION
    - source activate test

    # Python FSPS
    - python setup.py build_ext --inplace

script:
    - echo "hi"
